name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Passe das ggf. an deinen Haupt-Branch an

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # wichtig für hugo-tufte
          fetch-depth: 0    # notwendig für Hugo wegen Git info

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4' # oder aktuelle Version
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
